
# This pointcloud should be filtered and ready to fit
sensor_msgs/PointCloud2 in_cloud 

# Optional. Predicts the missing surfaces after the superellipsoid optimization task. 
bool enable_find_missing_surfaces

# Optional. Overrides config for a single service call. Check the example contents with 'rostopic echo -n1 /superellipsoid_detector_node/parameter_updates'
dynamic_reconfigure/Config config_override 

---

superellipsoid_msgs/Superellipsoid result

# Possibly non-empty if enable_find_missing_surfaces set to true
sensor_msgs/PointCloud2 missing_surfaces